name: elo-sac
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - absl-py
  - pyparsing
  - pillow
  - pip
  - pip:
    - numpy
    - termcolor
    - gym==0.25.1
    - dm_control
    - git+https://github.com/1nadequacy/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - scikit-image
    - setproctitle
    - scipy
